### ISSUE TITLE
Browser crash Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by jurjendevries** [zmeyer44/flockstr#2]
I created a calendar and posted an event. After posting the event the browser is crashing at https://www.flockstr.com/calendar/naddr1qqyrzvnx893xgvecqy8hwumn8ghj7mn0wd68ytnddaksyg8lhjmsd8m65htdky57kw08mz5h39rx6f26vda6c84lsctmq46qgspsgqqq0j6qqjmtj6
I tried multiple browsers such as Brave, Chrome and Firefox, but they all crash with this URL.

**Comment by zmeyer44** [comment]
Just pushed a fix for this!
